### ISSUE TITLE
[MCHANGELOG-54] NPE during "Developer Activity" report generation

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changelog-plugin#105]
**[David Vicente](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dvicente72)** opened **[MCHANGELOG-54](https://issues.apache.org/jira/browse/MCHANGELOG-54?redirect=false)** and commented

I'm using the maven-changelog-plugin:2.0-SNAPSHOT and i have a NullPointerException during "Developer Activity" report generation.

java.lang.NullPointerException at org.apache.maven.plugin.changelog.ChangeLogReport.countFilesChanged(ChangeLogReport.java:889)
at org.apache.maven.plugin.changelog.DeveloperActivityReport.doSummary(DeveloperActivityReport.java:221)
at org.apache.maven.plugin.changelog.DeveloperActivityReport.doChangedSets(DeveloperActivityReport.java:180)
at org.apache.maven.plugin.changelog.DeveloperActivityReport.doGenerateReport(DeveloperActivityReport.java:146)
at org.apache.maven.plugin.changelog.ChangeLogReport.executeReport(ChangeLogReport.java:296)

I have the Synergy SCM.

it occurs when a Synergy task is completed without modified file, the changelog.xml has an entry without file.

it occurs with the last released version.

I made the correction (see changelog-patch.txt) and it works fine

---

**Affects:** 2.0-beta-1

**Attachments:**
- [changelog-patch.txt](https://issues.apache.org/jira/secure/attachment/12714429/changelog-patch.txt) (_1.90 kB_)
- [changelog-patch-2.txt](https://issues.apache.org/jira/secure/attachment/12714430/changelog-patch-2.txt) (_5.48 kB_)

**Issue Links:**
- [SCM-283](https://issues.apache.org/jira/browse/SCM-283) getFiles() in ChangeSet can return null
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[David Vicente](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dvicente72)** commented

the first changelog-patch.txt contains only the correction for ChangeLogReport.

use the changelog-patch-2.txt for the 3 classes as described above

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

It's better to fix this in the Synergy SCM provider.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

The Synergy provider has been fixed, a new release of SCM has been made and the this plugin is using that latest release. I've deployed a new 2.1-SNAPSHOT of this plugin. Could you have a go and verify that this problem has been fixed?

**Comment by jira-importer** [comment]
**[David Vicente](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dvicente72)** commented

I have tested the new 2.1-SNAPSHOT version and for me it's ok.

You can close this issue.

thanks
