### ISSUE TITLE
[MCHANGELOG-95] Getting historical information from Microsoft Visual source is not working

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changelog-plugin#135]
**[Radhakrishnan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=radkrish5)** opened **[MCHANGELOG-95](https://issues.apache.org/jira/browse/MCHANGELOG-95?redirect=false)** and commented

file's creaion date is defined as in VSS 4/08/09 8:47p. I am getting below error when trying to execute changelog report. I tried using the dateformat as M/dd/yy hh:mma as well as M/dd/yy hh:mm & MM/dd/yy h:mm. But no options worked out.
java.text.ParseException: Unparseable date: "4/08/09 8:47p"
at java.text.DateFormat.parse(DateFormat.java:335)
at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:106)
at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:68)
at org.apache.maven.scm.provider.vss.commands.changelog.VssChangeLogConsumer.processGetAuthor(VssChangeLogConsumer.java:198)
at org.apache.maven.scm.provider.vss.commands.changelog.VssChangeLogConsumer.consumeLine(VssChangeLogConsumer.java:147)
at org.codehaus.plexus.util.cli.StreamPumper.consumeLine(StreamPumper.java:194)
at org.codehaus.plexus.util.cli.StreamPumper.run(StreamPumper.java:143)

---

**Affects:** 2.1

**Attachments:**
- [dateFormatNotBeingPassed](https://issues.apache.org/jira/secure/attachment/12714468/dateFormatNotBeingPassed) (_2.01 kB_)

**Comment by jira-importer** [comment]
**[Mateus Pimenta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=matpimenta)** commented

I had the same problem here. From the source code, the dateFormat is only used for 'range' type reports which is not stated in the documentation. IMO, it should accepted for all types as they will need to parse dates.
I'm submitting a patch to correct that.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
