### ISSUE TITLE
[MCHANGELOG-104] NPE when using the plugin with the git provider

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changelog-plugin#139]
**[Maarten Billemont](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lhunath)** opened **[MCHANGELOG-104](https://issues.apache.org/jira/browse/MCHANGELOG-104?redirect=false)** and commented

I've manually added a dependency on the gitexe provider to make the plugin able to use it.  However, using the plugin with GIT then causes the following NullPointerEception:

Caused by: java.lang.NullPointerException
at org.apache.maven.scm.ChangeSet.toXML(ChangeSet.java:425)
at org.apache.maven.scm.command.changelog.ChangeLogSet.toXML(ChangeLogSet.java:198)
at org.apache.maven.plugin.changelog.ChangeLogReport.writeChangelogXml(ChangeLogReport.java:421)
at org.apache.maven.plugin.changelog.ChangeLogReport.getChangedSets(ChangeLogReport.java:397)
at org.apache.maven.plugin.changelog.ChangeLogReport.executeReport(ChangeLogReport.java:340)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:98)
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:73)
... 19 more

---

**Affects:** 2.1

**Issue Links:**
- [MCHANGELOG-92](https://issues.apache.org/jira/browse/MCHANGELOG-92) update to maven-scm:1.3 to have the gitexe provider

2 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

Are you using plugin trunk ?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

The current 2.2-SNAPSHOT of this plugin has had the SCM component upgraded to version 1.3. Could you please test 2.2-SNAPSHOT to see if it resolves this issue.
