### ISSUE TITLE
[MCHANGELOG-116] java.text.ParseException: Unparseable date

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changelog-plugin#150]
**[Dennys Sanches](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennys)** opened **[MCHANGELOG-116](https://issues.apache.org/jira/browse/MCHANGELOG-116?redirect=false)** and commented

I can use Maven to get the source code from ClearCase and build file. And I want to use the changelog plugin and my goal is "-e clean -Dmaven.test.skip=true compile package changelog:changelog"

But I got the following error. I'm not sure this is changelog's error or clearcase plugin's. Is there any suggestion for it?

java.text.ParseException: Unparseable date: "20101011.160459"
at java.text.DateFormat.parse(DateFormat.java:337)
at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:112)
at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:68)
at org.apache.maven.scm.provider.clearcase.command.changelog.ClearCaseChangeLogConsumer.processGetDate(ClearCaseChangeLogConsumer.java:161)
at org.apache.maven.scm.provider.clearcase.command.changelog.ClearCaseChangeLogConsumer.consumeLine(ClearCaseChangeLogConsumer.java:120)
at org.codehaus.plexus.util.cli.StreamPumper.consumeLine(StreamPumper.java:195)
at org.codehaus.plexus.util.cli.StreamPumper.run(StreamPumper.java:144)
[ERROR] skip ParseException: Unparseable date: "20101011.160459" during
parsing date 20101011.160459 with pattern yyyy-MM-dd HH:mm:ss with Locale en

btw, I found http://jira.codehaus.org/browse/MCHANGELOG-115, but I'm not sure is it the same problem because it's environment is subversion.

---

**Affects:** 2.2

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12714463/pom.xml) (_590 bytes_)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
