### ISSUE TITLE
[MCHANGELOG-141] Failure to generate changelog.xml with mercurial - need to upgrade to 1.9.4 version of Maven SCM

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changelog-plugin#174]
**[James MacNider](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jphorx)** opened **[MCHANGELOG-141](https://issues.apache.org/jira/browse/MCHANGELOG-141?redirect=false)** and commented

I've found that the maven-changelog-plugin will fail to generate a tag-based changelog.xml file when the SCM is mercurial.  This is actually a bug in the 1.8 version of the maven-scm-plugin.

My testing with a custom (built by me) version of maven-changelog-plugin that depends on version 1.9.4 of maven-scm-plugin worked fine.

---

**Affects:** 2.3

**Comment by jira-importer** [comment]
**[James MacNider](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jphorx)** commented

These are the failure logs I see with current 2.3 version of maven-changelog-plugin:

```

[DEBUG] Generating /home/bob/components/mycomponent/target/site/changelog.html
[INFO] Generating "Change Log" report           --- maven-changelog-plugin:2.3:changelog
[INFO] Generating changed sets xml to: /home/bob/components/mycomponent/target/changelog.xml
[INFO] EXECUTING: /bin/sh -c cd /home/bob/components/mycomponent && hg log '--template "changeset:   {rev}:{node|short}
branch:      {branch}
user:        {author}
date:        {date|isodatesec}
tag:         {tags}
files:       {files}
description:
{desc}

"' --no-merges -r tip:1.3.0
[WARNING] Could not figure out: hg log: option --template "changeset:   {rev}:{node|short}
[WARNING] Could not figure out: branch:      {branch}
[WARNING] skip ParseException: Unparseable date: "{date|isodatesec}" during parsing date {date|isodatesec} with pattern yyyy-MM-dd HH:mm:ss Z with Locale en
java.text.ParseException: Unparseable date: "{date|isodatesec}"
	at java.text.DateFormat.parse(DateFormat.java:357)
	at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:112)
	at org.apache.maven.scm.provider.hg.command.changelog.HgChangeLogConsumer.doConsume(HgChangeLogConsumer.java:161)
	at org.apache.maven.scm.provider.hg.command.changelog.HgChangeLogConsumer.consumeLine(HgChangeLogConsumer.java:92)
	at org.codehaus.plexus.util.cli.StreamPumper.consumeLine(StreamPumper.java:190)
	at org.codehaus.plexus.util.cli.StreamPumper.run(StreamPumper.java:135)
[ERROR] 
EXECUTION FAILED
  Execution of cmd : log failed with exit code: 255.
  Working directory was: 
    /home/bob/components/mycomponent
  Your Hg installation seems to be valid and complete.
    Hg version: 2.9 (OK)


[ERROR] Provider message:
[ERROR] 
EXECUTION FAILED
  Execution of cmd : log failed with exit code: 255.
  Working directory was: 
    /home/bob/components/mycomponent
  Your Hg installation seems to be valid and complete.
    Hg version: 2.9 (OK)


[ERROR] Command output:
[ERROR] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.444s
[INFO] Finished at: Wed Oct 07 19:44:48 GMT 2015
[INFO] Final Memory: 28M/225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project mycomponent: Error generating maven-changelog-plugin:2.3:changelog: An error has occurred during changelog command : Command failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project mycomponent: Error generating maven-changelog-plugin:2.3:changelog: An error has occurred during changelog command : 
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating maven-changelog-plugin:2.3:changelog: An error has occurred during changelog command : 
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:146)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.apache.maven.doxia.siterenderer.RendererException: Error generating maven-changelog-plugin:2.3:changelog: An error has occurred during changelog command : 
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:239)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:311)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:129)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:182)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:141)
	... 21 more
Caused by: org.apache.maven.reporting.MavenReportException: An error has occurred during changelog command : 
	at org.apache.maven.plugin.changelog.ChangeLogReport.generateChangeSetsFromSCM(ChangeLogReport.java:739)
	at org.apache.maven.plugin.changelog.ChangeLogReport.getChangedSets(ChangeLogReport.java:563)
	at org.apache.maven.plugin.changelog.ChangeLogReport.executeReport(ChangeLogReport.java:477)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:196)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:224)
	... 25 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Command failed.
	at org.apache.maven.plugin.changelog.ChangeLogReport.checkResult(ChangeLogReport.java:986)
	at org.apache.maven.plugin.changelog.ChangeLogReport.generateChangeSetsFromSCM(ChangeLogReport.java:675)
	... 29 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by jira-importer** [comment]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** commented

sounds like this one is now fixed
