### ISSUE TITLE
[MCHANGELOG-2] changelog (2.0-beta-2-SNAPSHOT) NPEs when reading changelog.xml

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changelog-plugin#47]
**[skaze](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=skaze)** opened **[MCHANGELOG-2](https://issues.apache.org/jira/browse/MCHANGELOG-2?redirect=false)** and commented

First time its run plugin works okay:-

D:\Aelitis\projects\examples\utils\aelitis-utils-logging>abs -X changelog:changelog
[INFO] Automatic Build System, Version: 1.0-SNAPSHOT
[INFO] Using ABS_ROOT location: D:\Aelitis
[INFO] Using JAVA_HOME location: D:\Aelitis\tools\j2sdk1.4.2_08
[INFO] Using local repostitory: D:\Aelitis\local-repository
[INFO] Using MAVEN_HOME location: D:\Aelitis\tools\maven-2.1-SNAPSHOT
[INFO] Using MAVEN_CLI arguments: -X changelog:changelog
[INFO] Using MAVEN_OPTS options:  -Xmx512m -Dabs.build=true -Dmaven.repo.local=D:\Aelitis\local-repository
+ Error stacktraces are turned on.
  [DEBUG] Building Maven user-level plugin registry from: 'D:\profiles\John\.m2\plugin-registry.xml'
  [DEBUG] Building Maven global-level plugin registry from: 'D:\Aelitis\tools\maven-2.1-SNAPSHOT\conf\plugin-registry.xml'
  [INFO] Scanning for projects...
  [DEBUG] Using parent-POM from the project hierarchy at: '../pom.xml' for project: com.aelitis.examples.utils:aelitis-utils-logging:jar:1.1-S
  NAPSHOT
  [DEBUG] Using parent-POM from the project hierarchy at: '../pom.xml' for project: com.aelitis.examples:utils:pom:1.1-SNAPSHOT
  [DEBUG] Retrieving parent-POM from the repository for project: com.aelitis:examples:pom:1.1-SNAPSHOT
  [DEBUG] Skipping disabled repository central
  [DEBUG] root: using locally installed snapshot
  [INFO] Searching repository for plugin with prefix: 'changelog'.
  [DEBUG] Skipping disabled repository central
  [DEBUG] Skipping disabled repository company-plugin-snapshot-repository
  [DEBUG] Skipping disabled repository central
  [DEBUG] Skipping disabled repository company-plugin-snapshot-repository
  [DEBUG] Skipping disabled repository central
  [DEBUG] Skipping disabled repository company-plugin-snapshot-repository
  [DEBUG] changelog-maven-plugin: resolved to version 2.0-beta-2-SNAPSHOT from local repository
  [DEBUG] Skipping disabled repository central
  [DEBUG] Skipping disabled repository company-plugin-release-repository
  [DEBUG] changelog-maven-plugin: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: null:changelog-maven-plugin:maven-plugin:2.0-beta-2-SNAPSHOT
  [DEBUG] changelog-maven-plugin: using locally installed snapshot
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building Logging Utilities
  [INFO]    task-segment: [changelog:changelog]
  [INFO] ----------------------------------------------------------------------------
  [DEBUG] org.codehaus.mojo:changelog-maven-plugin:maven-plugin:2.0-beta-2-SNAPSHOT (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-model:jar:2.0
  [DEBUG]   org.apache.maven:maven-model:jar:2.0 (selected for runtime)
  [DEBUG]     org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG]   netbeans:cvslib:jar:3.6 (selected for runtime)
  [DEBUG]   ant:ant:jar:1.6.5 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-project:jar:2.0
  [DEBUG]   org.apache.maven:maven-project:jar:2.0 (selected for runtime)
  [DEBUG]     org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-8 (selected for runtime)
  [DEBUG]       classworlds:classworlds:jar:1.1-alpha-2 (selected for runtime)
  [DEBUG]       junit:junit:jar:3.8.1 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-artifact:jar:2.0
  [DEBUG]     org.apache.maven:maven-artifact:jar:2.0 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-artifact-manager:jar:2.0
  [DEBUG]     org.apache.maven:maven-artifact-manager:jar:2.0 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-repository-metadata:jar:2.0
  [DEBUG]       org.apache.maven:maven-repository-metadata:jar:2.0 (selected for runtime)
  [DEBUG]       org.apache.maven.wagon:wagon-provider-api:jar:1.0-alpha-5 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-profile:jar:2.0
  [DEBUG]     org.apache.maven:maven-profile:jar:2.0 (selected for runtime)
  [DEBUG]   doxia:doxia-sink-api:jar:1.0-alpha-5 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-reporting-api:jar:2.0
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven.reporting:maven-reporting:pom:2.0
  [DEBUG]   org.apache.maven.reporting:maven-reporting-api:jar:2.0 (selected for runtime)
  [DEBUG]     doxia:doxia-sink-api:jar:1.0-alpha-4 (removed - nearer found: 1.0-alpha-5)
  [DEBUG]   regexp:regexp:jar:1.3 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-reporting-impl:jar:2.0
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven.reporting:maven-reporting:pom:2.0
  [DEBUG]   org.apache.maven.reporting:maven-reporting-impl:jar:2.0 (selected for runtime)
  [DEBUG]     commons-validator:commons-validator:jar:1.1.4 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-plugin-api:jar:2.0
  [DEBUG]     org.apache.maven:maven-plugin-api:jar:2.0 (selected for runtime)
  [DEBUG]     oro:oro:jar:2.0.7 (selected for runtime)
  [DEBUG]     doxia:doxia-core:jar:1.0-alpha-4 (selected for runtime)
  [DEBUG]       doxia:doxia-sink-api:jar:1.0-alpha-4 (removed - nearer found: 1.0-alpha-5)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-plugin-api:jar:2.0-beta-1
  [DEBUG]   org.apache.maven:maven-plugin-api:jar:2.0 (removed - nearer found: 2.0-beta-1)
  [DEBUG]   org.apache.maven:maven-plugin-api:jar:2.0-beta-1 (selected for runtime)
  [DEBUG] Configuring mojo 'org.codehaus.mojo:changelog-maven-plugin:2.0-beta-2-SNAPSHOT:changelog' -->
  [DEBUG]   (f) basedir = D:\Aelitis\projects\examples\utils\aelitis-utils-logging
  [DEBUG]   (f) dateFormat = yyyy-MM-dd
  [DEBUG]   (f) offline = false
  [DEBUG]   (f) outputDirectory = D:\Aelitis\projects\examples\utils\aelitis-utils-logging\target\site
  [DEBUG]   (f) outputEncoding = ISO-8859-1
  [DEBUG]   (f) outputXML = D:\Aelitis\projects\examples\utils\aelitis-utils-logging\target\changelog.xml
  [DEBUG]   (f) project = org.apache.maven.project.MavenProject@9fba273
  [DEBUG]   (f) scmUrl = http://allenj4lt1/viewcvs/projects/examples/trunk/utils/aelitis-utils-logging
  [DEBUG]   (f) type = range
  [DEBUG]   - end configuration --
  [INFO] [changelog:changelog]
  [INFO] Generating changed sets xml to: D:\Aelitis\projects\examples\utils\aelitis-utils-logging\target\changelog.xml
  [INFO] SCM Working Directory: D:\Aelitis\projects\examples\utils\aelitis-utils-logging
  [INFO] SCM Command Line[0]: svn
  [INFO] SCM Command Line[1]: log
  [INFO] SCM Command Line[2]: -v
  [INFO] SCM Command Line[3]: "-r{2006-01-11}:{2005-12-11}"
  [INFO] ChangeSet between 2005-12-11 and 2006-01-11: 2 entries
  [INFO] ----------------------------------------------------------------------------
  [INFO] BUILD SUCCESSFUL
  [INFO] ----------------------------------------------------------------------------
  [INFO] Total time: 3 seconds
  [INFO] Finished at: Tue Jan 10 10:56:59 GMT 2006
  [INFO] Final Memory: 2M/5M
  [INFO] ----------------------------------------------------------------------------

running again results in NPE :-

D:\Aelitis\projects\examples\utils\aelitis-utils-logging>abs -X changelog:changelog
[INFO] Automatic Build System, Version: 1.0-SNAPSHOT
[INFO] Using ABS_ROOT location: D:\Aelitis
[INFO] Using JAVA_HOME location: D:\Aelitis\tools\j2sdk1.4.2_08
[INFO] Using local repostitory: D:\Aelitis\local-repository
[INFO] Using MAVEN_HOME location: D:\Aelitis\tools\maven-2.1-SNAPSHOT
[INFO] Using MAVEN_CLI arguments: -X changelog:changelog
[INFO] Using MAVEN_OPTS options:  -Xmx512m -Dabs.build=true -Dmaven.repo.local=D:\Aelitis\local-repository
+ Error stacktraces are turned on.
  [DEBUG] Building Maven user-level plugin registry from: 'D:\profiles\John\.m2\plugin-registry.xml'
  [DEBUG] Building Maven global-level plugin registry from: 'D:\Aelitis\tools\maven-2.1-SNAPSHOT\conf\plugin-registry.xml'
  [INFO] Scanning for projects...
  [DEBUG] Using parent-POM from the project hierarchy at: '../pom.xml' for project: com.aelitis.examples.utils:aelitis-utils-logging:jar:1.1-S
  NAPSHOT
  [DEBUG] Using parent-POM from the project hierarchy at: '../pom.xml' for project: com.aelitis.examples:utils:pom:1.1-SNAPSHOT
  [DEBUG] Retrieving parent-POM from the repository for project: com.aelitis:examples:pom:1.1-SNAPSHOT
  [DEBUG] Skipping disabled repository central
  [DEBUG] root: using locally installed snapshot
  [INFO] Searching repository for plugin with prefix: 'changelog'.
  [DEBUG] Skipping disabled repository central
  [DEBUG] Skipping disabled repository company-plugin-snapshot-repository
  [DEBUG] Skipping disabled repository central
  [DEBUG] Skipping disabled repository company-plugin-snapshot-repository
  [DEBUG] Skipping disabled repository central
  [DEBUG] Skipping disabled repository company-plugin-snapshot-repository
  [DEBUG] changelog-maven-plugin: resolved to version 2.0-beta-2-SNAPSHOT from local repository
  [DEBUG] Skipping disabled repository central
  [DEBUG] Skipping disabled repository company-plugin-release-repository
  [DEBUG] changelog-maven-plugin: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: null:changelog-maven-plugin:maven-plugin:2.0-beta-2-SNAPSHOT
  [DEBUG] changelog-maven-plugin: using locally installed snapshot
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building Logging Utilities
  [INFO]    task-segment: [changelog:changelog]
  [INFO] ----------------------------------------------------------------------------
  [DEBUG] org.codehaus.mojo:changelog-maven-plugin:maven-plugin:2.0-beta-2-SNAPSHOT (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-model:jar:2.0
  [DEBUG]   org.apache.maven:maven-model:jar:2.0 (selected for runtime)
  [DEBUG]     org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG]   netbeans:cvslib:jar:3.6 (selected for runtime)
  [DEBUG]   ant:ant:jar:1.6.5 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-project:jar:2.0
  [DEBUG]   org.apache.maven:maven-project:jar:2.0 (selected for runtime)
  [DEBUG]     org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-8 (selected for runtime)
  [DEBUG]       classworlds:classworlds:jar:1.1-alpha-2 (selected for runtime)
  [DEBUG]       junit:junit:jar:3.8.1 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-artifact:jar:2.0
  [DEBUG]     org.apache.maven:maven-artifact:jar:2.0 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-artifact-manager:jar:2.0
  [DEBUG]     org.apache.maven:maven-artifact-manager:jar:2.0 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-repository-metadata:jar:2.0
  [DEBUG]       org.apache.maven:maven-repository-metadata:jar:2.0 (selected for runtime)
  [DEBUG]       org.apache.maven.wagon:wagon-provider-api:jar:1.0-alpha-5 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-profile:jar:2.0
  [DEBUG]     org.apache.maven:maven-profile:jar:2.0 (selected for runtime)
  [DEBUG]   doxia:doxia-sink-api:jar:1.0-alpha-5 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-reporting-api:jar:2.0
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven.reporting:maven-reporting:pom:2.0
  [DEBUG]   org.apache.maven.reporting:maven-reporting-api:jar:2.0 (selected for runtime)
  [DEBUG]     doxia:doxia-sink-api:jar:1.0-alpha-4 (removed - nearer found: 1.0-alpha-5)
  [DEBUG]   regexp:regexp:jar:1.3 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-reporting-impl:jar:2.0
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven.reporting:maven-reporting:pom:2.0
  [DEBUG]   org.apache.maven.reporting:maven-reporting-impl:jar:2.0 (selected for runtime)
  [DEBUG]     commons-validator:commons-validator:jar:1.1.4 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-plugin-api:jar:2.0
  [DEBUG]     org.apache.maven:maven-plugin-api:jar:2.0 (selected for runtime)
  [DEBUG]     oro:oro:jar:2.0.7 (selected for runtime)
  [DEBUG]     doxia:doxia-core:jar:1.0-alpha-4 (selected for runtime)
  [DEBUG]       doxia:doxia-sink-api:jar:1.0-alpha-4 (removed - nearer found: 1.0-alpha-5)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-plugin-api:jar:2.0-beta-1
  [DEBUG]   org.apache.maven:maven-plugin-api:jar:2.0 (removed - nearer found: 2.0-beta-1)
  [DEBUG]   org.apache.maven:maven-plugin-api:jar:2.0-beta-1 (selected for runtime)
  [DEBUG] Configuring mojo 'org.codehaus.mojo:changelog-maven-plugin:2.0-beta-2-SNAPSHOT:changelog' -->
  [DEBUG]   (f) basedir = D:\Aelitis\projects\examples\utils\aelitis-utils-logging
  [DEBUG]   (f) dateFormat = yyyy-MM-dd
  [DEBUG]   (f) offline = false
  [DEBUG]   (f) outputDirectory = D:\Aelitis\projects\examples\utils\aelitis-utils-logging\target\site
  [DEBUG]   (f) outputEncoding = ISO-8859-1
  [DEBUG]   (f) outputXML = D:\Aelitis\projects\examples\utils\aelitis-utils-logging\target\changelog.xml
  [DEBUG]   (f) project = org.apache.maven.project.MavenProject@9fba273
  [DEBUG]   (f) scmUrl = http://allenj4lt1/viewcvs/projects/examples/trunk/utils/aelitis-utils-logging
  [DEBUG]   (f) type = range
  [DEBUG]   - end configuration --
  [INFO] [changelog:changelog]
  [INFO] ----------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ----------------------------------------------------------------------------
  [INFO] An error has occurred in changelog report generation.

Embedded error: An error occurred while parsing D:\Aelitis\projects\examples\utils\aelitis-utils-logging\target\changelog.xml
java.lang.NullPointerException
[INFO] ----------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: An error has occurred in changelog report generation.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:555)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:485)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:455)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in changelog report generation.
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:79)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:432)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:530)
... 16 more
Caused by: org.apache.maven.reporting.MavenReportException: An error occurred while parsing D:\Aelitis\projects\examples\utils\aelitis-utils
-logging\target\changelog.xml
at org.apache.maven.changelog.ChangeLogReport.getChangedSets(ChangeLogReport.java:212)
at org.apache.maven.changelog.ChangeLogReport.executeReport(ChangeLogReport.java:180)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:98)
at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:73)
... 18 more
Caused by: java.lang.NullPointerException
at org.apache.crimson.parser.Parser2.parseInternal(Parser2.java:691)
at org.apache.crimson.parser.Parser2.parse(Parser2.java:337)
at org.apache.crimson.parser.XMLReaderImpl.parse(XMLReaderImpl.java:448)
at javax.xml.parsers.SAXParser.parse(SAXParser.java:345)
at javax.xml.parsers.SAXParser.parse(SAXParser.java:143)
at org.apache.maven.changelog.ChangeLog.loadChangedSets(ChangeLog.java:701)
at org.apache.maven.changelog.ChangeLogReport.getChangedSets(ChangeLogReport.java:199)
... 21 more
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 3 seconds
[INFO] Finished at: Tue Jan 10 10:57:28 GMT 2006
[INFO] Final Memory: 2M/5M
[INFO] ----------------------------------------------------------------------------

if you delete the changelog.xml and run again it works.

However, regardless of whether there is an existing changelog.xml file present running the plugin from the site:site mojo results in a NPE EVERY time.

Eg.

mvn site:site

\<snip/>

[ERROR] VM #displayTree: error : too few arguments to macro. Wanted 2 got 0
[ERROR] VM #menuItem: error : too few arguments to macro. Wanted 1 got 0
[INFO] Generate "Checkstyle" report.
[INFO] There are 10 checkstyle errors.
[INFO] Generate "Clover" report.
Clover Version 1.3.11, built on November 02 2005
loaded from: D:\Aelitis\local-repository\clover\clover\1.3.11\clover-1.3.11.jar
30 day Evaluation Version distributed via the Maven Jar Repository.
Clover is not free. You have 30 days to evaluate it. After this, please visit http://www.cenqua.com to obtain a licensed version of Clover
WARN: No coverage data found for 'D:\Aelitis\projects\examples\utils\aelitis-utils-logging\target/clover/clover.db'.
WARN: No coverage recordings found. No report will be generated.
[INFO] Generate "PMD Report" report.
[WARNING] Unable to locate rule set: java.io.IOException: Unable to find location '/ruleset/controversial.xml' as URL, File or Resource.
[INFO] Generate "JDepend" report.
[INFO] Generate "changelog" report.
[INFO] Generating changed sets xml to: D:\Aelitis\projects\examples\utils\aelitis-utils-logging\target\changelog.xml
[INFO] SCM Working Directory: D:\Aelitis\projects\examples\utils\aelitis-utils-logging
[INFO] SCM Command Line[0]: svn
[INFO] SCM Command Line[1]: log
[INFO] SCM Command Line[2]: -v
[INFO] SCM Command Line[3]: "-r{2006-01-11}:{2005-12-11}"
[INFO] ChangeSet between 2005-12-11 and 2006-01-11: 2 entries
[INFO] Generate "dev-activity" report.
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Error during report generation

Embedded error: An error occurred while parsing D:\Aelitis\projects\examples\utils\aelitis-utils-logging\target\changelog.xml
java.lang.NullPointerException
[INFO] ----------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 32 seconds
[INFO] Finished at: Tue Jan 10 11:00:14 GMT 2006
[INFO] Final Memory: 17M/31M
[INFO] ----------------------------------------------------------------------------

Reverting to 2.0-beta-1 fixes the problem.

---

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

Fixed in SVN
