### ISSUE TITLE
[MCHANGELOG-36] Tests fail on build

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changelog-plugin#48]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** opened **[MCHANGELOG-36](https://issues.apache.org/jira/browse/MCHANGELOG-36?redirect=false)** and commented

The date test assertions all fail:

junit.framework.AssertionFailedError: Test changelog 1 set 1 date/time expected:<239635800000> but was:< 239715000000 >
at org.apache.maven.changelog.ChangeLogTest.testReadFile(ChangeLogTest.java:50)

    assertEquals( "Test changelog 1 set 1 date/time", 239635800000L, changeSet.getDate().getTime() );

They just have the wrong date, and they are offset by the timezone ( 7 hours, in my case - I'm MST -0700)

---

**Affects:** 2.0

**Attachments:**
- [MCHANGELOG-36.patch](https://issues.apache.org/jira/secure/attachment/12714427/MCHANGELOG-36.patch) (_2.93 kB_)
- [MCHANGELOG-36a.patch](https://issues.apache.org/jira/secure/attachment/12714426/MCHANGELOG-36a.patch) (_3.86 kB_)

**Issue Links:**
- [MCHANGELOG-68](https://issues.apache.org/jira/browse/MCHANGELOG-68) testReadFile unit test timebased comparisons fail

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

I get also an error

---

Test set: org.apache.maven.changelog.ChangeLogTest

---

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec <<< FAILURE!
testReadFile(org.apache.maven.changelog.ChangeLogTest)  Time elapsed: 0.015 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Test changelog 1 set 1 date/time expected:<239635800000> but was:<239747400000>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:136)
at org.apache.maven.changelog.ChangeLogTest.testReadFile(ChangeLogTest.java:50)

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

I think the real problem is that we don't get the timezone information into the changelog.xml. Thus I made the assumption that all change entries were in the timezone of the person creating the site, and just used that timezone to correct the date entry. I don't think that assumption is going to hold up. Let me see if I can correct the real problem.

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

MCHANGELOG-36a.patch does the following. It assumes that the change entry was made using the default time zone (on the machine invoking the changelog plugin). This assumption is made because the changelog.xml produced from scm reflects nothing about the timezone information of the event. To properly fix this problem, changes to maven-scm would need to be made. Either a new timezone element is needed, or the time element should not omit the timezone information that came from scm.

When a Date is created while parsing the changelog.xml file, we adjust for the default timezone. Otherwise the Date created will not reflect the date in the changelog.xml - it will be offset by the timezone.

ChangeLogTest.java is also modified so that tests will work no matter what the default timezone of the machine building the plugin.

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

MCHANGELOG-36a.patch supercedes MCHANGELOG-36.patch (ie ignore or delete MCHANGELOG-36.patch)

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

While this patch is fine on it's own, if one then tries to apply the MCHANGELOG-3.patch, it won't work. Do it in the opposite order:

MCHANGELOG-3.patch
MCHANGELOG-36a.patch

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

Patch applied. Thanks.
