### ISSUE TITLE
[MCHANGELOG-8] Changelog using <connection> not <developerConnection>

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-changelog-plugin#65]
**[Alex Mayorga Adame](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alex_mayorga)** opened **[MCHANGELOG-8](https://issues.apache.org/jira/browse/MCHANGELOG-8?redirect=false)** and commented

Looks like changelog uses \<connection> and needs to lock directories in CVS to produce its report. http://maven.apache.org/ref/2.0.3-SNAPSHOT/maven-model/maven.html#class_scm states that \<connection> is to be read-only.

Below found case for a \<connection> read-only that fails:

mvn scm:changelog -X
+ Error stacktraces are turned on.
  [DEBUG] Building Maven user-level plugin registry from: '/home/alexito/.m2/plugin-registry.xml'
  [DEBUG] Building Maven global-level plugin registry from: '/Maven/2.0.1/conf/plugin-registry.xml'
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'scm'.
  [DEBUG] maven-antrun-plugin: resolved to version 1.1 from repository central
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-antrun-plugin:maven-plugin:1.1
  [DEBUG] maven-scm-plugin: resolved to version 1.0-beta-2 from repository central
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven.plugins:maven-scm-plugin:maven-plugin:1.0-beta-2
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building ESF Sample Project
  [INFO]    task-segment: [scm:changelog] (aggregator-style)
  [INFO] ----------------------------------------------------------------------------
  [DEBUG] org.apache.maven.plugins:maven-scm-plugin:maven-plugin:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-settings:jar:2.0
  [DEBUG]   org.apache.maven:maven-settings:jar:2.0 (selected for runtime)
  [DEBUG]     org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG]     org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-8 (selected for runtime)
  [DEBUG]       classworlds:classworlds:jar:1.1-alpha-2 (selected for runtime)
  [DEBUG]       junit:junit:jar:3.8.1 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-model:jar:2.0
  [DEBUG]     org.apache.maven:maven-model:jar:2.0 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-cvs:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-cvs:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-api:jar:1.0-beta-2
  [DEBUG]     org.apache.maven.scm:maven-scm-api:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-local:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-local:jar:1.0-beta-2 (selected for runtime)
  [DEBUG]   org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-starteam:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-starteam:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-manager-plexus:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-managers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-manager-plexus:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: plexus:plexus-container-default:jar:1.0-alpha-5
  [DEBUG] Retrieving parent-POM from the repository for project: plexus:plexus-containers:pom:1.0
  [DEBUG]     plexus:plexus-container-default:jar:1.0-alpha-5 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: plexus:plexus-utils:jar:1.0.1
  [DEBUG]       plexus:plexus-utils:jar:1.0.1 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-clearcase:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-clearcase:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-perforce:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-perforce:jar:1.0-beta-2 (selected for runtime)
  [DEBUG]     regexp:regexp:jar:1.3 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-plugin-api:jar:2.0
  [DEBUG]   org.apache.maven:maven-plugin-api:jar:2.0 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-svn:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-svn:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-scm-plugin:1.0-beta-2:changelog' -->
  [DEBUG]   (f) basedir = /home/am74839/esfSample
  [DEBUG]   (f) connectionUrl = scm:cvs:pserver:anonymous:`@somewhere`.com:/export1/cvs/gtpl:esfSample
  [DEBUG]   (f) settings = org.apache.maven.settings.Settings@3dc0bb
  [DEBUG]   - end configuration --
  [INFO] [scm:changelog]
  [DEBUG] cvsRoot: :pserver:anonymous@somewhere.com:2401/export1/cvs/gtpl
  [DEBUG] passFile: /home/alexito/.cvspass
  [DEBUG] cvsroot :pserver:anonymous@somewhere.com:2401/export1/cvs/gtpl already exist in /home/alexito/.cvspass. SKIPPED.
  [DEBUG] Working directory: /home/alexito/esfSample
  [DEBUG] Command line: cvs -z3 -f -d :pserver:anonymous@somewhere.com:/export1/cvs/gtpl -q log
  [ERROR] Provider message:
  [ERROR] The cvs command failed.
  [ERROR] Command output:
  [ERROR] cvs server: failed to create lock directory for `/export1/cvs/gtpl/esfSample' (/export1/cvs/gtpl/esfSample/#cvs.lock): Permission denied
  cvs server: failed to obtain dir lock in repository `/export1/cvs/gtpl/esfSample'
  cvs [server aborted]: read lock failed - giving up

[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Command failed.
[INFO] ----------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Command failed.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:555)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:485)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:455)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:216)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command failed.
at org.apache.maven.scm.plugin.AbstractScmMojo.checkResult(AbstractScmMojo.java:252)
at org.apache.maven.scm.plugin.ChangeLogMojo.execute(ChangeLogMojo.java:74)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:432)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:530)
... 16 more
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 11 seconds
[INFO] Finished at: Fri Mar 10 16:41:25 EST 2006
[INFO] Final Memory: 2M/7M
[INFO] ----------------------------------------------------------------------------

Here's same goal with a read-write \<connection> that succeds:

mvn scm:changelog -X
+ Error stacktraces are turned on.
  [DEBUG] Building Maven user-level plugin registry from: '/home/alexito/.m2/plugin-registry.xml'
  [DEBUG] Building Maven global-level plugin registry from: '/Maven/2.0.1/conf/plugin-registry.xml'
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'scm'.
  [DEBUG] maven-antrun-plugin: resolved to version 1.1 from repository central
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-antrun-plugin:maven-plugin:1.1
  [DEBUG] maven-scm-plugin: resolved to version 1.0-beta-2 from repository central
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven.plugins:maven-scm-plugin:maven-plugin:1.0-beta-2
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building ESF Sample Project
  [INFO]    task-segment: [scm:changelog] (aggregator-style)
  [INFO] ----------------------------------------------------------------------------
  [DEBUG] org.apache.maven.plugins:maven-scm-plugin:maven-plugin:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-settings:jar:2.0
  [DEBUG]   org.apache.maven:maven-settings:jar:2.0 (selected for runtime)
  [DEBUG]     org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG]     org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-8 (selected for runtime)
  [DEBUG]       classworlds:classworlds:jar:1.1-alpha-2 (selected for runtime)
  [DEBUG]       junit:junit:jar:3.8.1 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-model:jar:2.0
  [DEBUG]     org.apache.maven:maven-model:jar:2.0 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-cvs:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-cvs:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-api:jar:1.0-beta-2
  [DEBUG]     org.apache.maven.scm:maven-scm-api:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-local:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-local:jar:1.0-beta-2 (selected for runtime)
  [DEBUG]   org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-starteam:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-starteam:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-manager-plexus:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-managers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-manager-plexus:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: plexus:plexus-container-default:jar:1.0-alpha-5
  [DEBUG] Retrieving parent-POM from the repository for project: plexus:plexus-containers:pom:1.0
  [DEBUG]     plexus:plexus-container-default:jar:1.0-alpha-5 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: plexus:plexus-utils:jar:1.0.1
  [DEBUG]       plexus:plexus-utils:jar:1.0.1 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-clearcase:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-clearcase:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-perforce:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-perforce:jar:1.0-beta-2 (selected for runtime)
  [DEBUG]     regexp:regexp:jar:1.3 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-plugin-api:jar:2.0
  [DEBUG]   org.apache.maven:maven-plugin-api:jar:2.0 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-provider-svn:jar:1.0-beta-2
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-scm-providers:pom:1.0-beta-2
  [DEBUG]   org.apache.maven.scm:maven-scm-provider-svn:jar:1.0-beta-2 (selected for runtime)
  [DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-scm-plugin:1.0-beta-2:changelog' -->
  [DEBUG]   (f) basedir = /home/alexito/esfSample
  [DEBUG]   (f) connectionUrl = scm:cvs:pserver:alexito:pass@somewhere.com:/opt/cvs/gtpl:esfSample
  [DEBUG]   (f) settings = org.apache.maven.settings.Settings@3dc0bb
  [DEBUG]   - end configuration --
  [INFO] [scm:changelog]
  [DEBUG] cvsRoot: :pserver:alexito@somewhere.com:2401/export1/cvs/gtpl
  [DEBUG] passFile: /home/alexito/.cvspass
  [DEBUG] cvsroot :pserver:alexito@somewhere.com:2401/export1/cvs/gtpl already exist in /home/alexito/.cvspass. SKIPPED.
  [DEBUG] Working directory: /home/alexito/esfSample
  [DEBUG] Command line: cvs -z3 -f -d :pserver:alexito@somewhere.com:/export1/cvs/gtpl -q log
  alexito
  Thu Mar 09 19:37:45 EST 2006
  README, 1.1
  branches:  1.1.1;
  Initial revision

...

[INFO] ----------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 13 seconds
[INFO] Finished at: Fri Mar 10 15:04:33 EST 2006
[INFO] Final Memory: 2M/7M
[INFO] ----------------------------------------------------------------------------

I believe the best approach would have changelog use \<developerConnection> instead.

---
No further details from [MCHANGELOG-8](https://issues.apache.org/jira/browse/MCHANGELOG-8?redirect=false)

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

I'm not sure about this issue because scm -> connection has always been used first before developerConnection way back in m1.

About the read-only thing, it maybe a server configuration that anonymous users may not retrieve logs because i don't think you'll need write access just to get the logs.

Or maybe its the implementation of maven-scm.  I'll have to ask evenisse about this.

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

There is now a new parameter, connectionType, which anyone can use to tell changelog which scm connection to use.  It can either be: "connection" or "developerConnection".  "connection" is still default.
